name: 01-building-blocks
on : push

jobs:

 job1:
  runs-on: ubuntu-latest
  steps: 
   - name: job1steps1
     run: echo "Hello world and steps1 output"
  

 job2:
  runs-on: ubuntu-latest
  steps: 
   - name: job2steps1
     run: |
      echo "this is second job output with error code 1 so it shows as fail"
      exit 0
   - name: job2steps2
     run: |
      echo "testing"
      

